name       : fprintd
version    : 1.90.1
release    : 2
source     :
    - https://gitlab.freedesktop.org/libfprint/fprintd/uploads/a47c31c844e23e070665a8a85dae0144/fprintd-1.90.1.tar.xz : b4940b1dfb052a3641f1bb9bc7685b649aaa26220016dd793871d4f421c8a30d
license    : GPL-2.0-or-later
component  : desktop.core
summary    : D-Bus service to access fingerprint readers
description: |
    Daemon to offer libfprint functionality over D-Bus
builddeps  :
    - pkgconfig(dbus-glib-1)
    - pkgconfig(dbus-python)
    - pkgconfig(gtk-doc)
    - pkgconfig(libfprint)
    - pkgconfig(pam_wrapper)
    - pkgconfig(py3cairo)
    - pkgconfig(pygobject-3.0)
    - python-dbusmock
setup      : |
    %meson_configure -Dpam_modules_dir=/lib/security
build      : |
    %ninja_build
install    : |
    %ninja_install
    install -Dm00644 $pkgfiles/fprintd.tmpfiles $installdir/%libdir%/tmpfiles.d/fprintd.conf
